spring:
  application:
    name: Pandemic
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
springdoc:
  swagger-ui:
    path: /swagger-ui.html
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
jwt:
  issuer-uris: ${JWT_ISSUER_URIS}
